JobBatchName            = "theMD"
docker_image            = docker://gromacs/gromacs:2022.2

# Artefact
executable              = run.sh
arguments               = $(protein)
transfer_input_files    = gromacs_pipeline.sh,mdp.tar.gz,inputs/$(protein).pdb
transfer_output_files   = data.tar.gz

# Logging
stream_output           = true
output                  = condor_log/output.$(Cluster)-$(Process).txt
error                   = condor_log/error.$(Cluster)-$(Process).txt
log                     = condor_log/log.$(Cluster)-$(Process).txt

# Compute resources
request_cpus            = 8
request_memory          = 16GB
request_disk            = 50GB

# Extra GPU settings
request_gpus            = 1
require_gpus            = GlobalMemoryMb >= 8000
+WantGPULab             = true
+GPUJobLength           = "short"
Requirements            = (Target.CUDADriverVersion >= 12.0)

queue protein from proteins.txt
