# build_motion_class_index.sub

docker_image = jenslundsgaard/sheaf_training:v2.0

universe = docker

shell = ./build_motion_class_index.sh 

log = build_motion_class_index_$(Cluster)_$(Process).log
error = build_motion_class_index_$(Cluster)_$(Process).err
output = build_motion_class_index_$(Cluster)_$(Process).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)

transfer_input_files = build_motion_class_index.sh, build_motion_class_index.py, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/free_bound_pocket.csv, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/bound_dif_ligand_pocket.csv ,../lib/pdb_api.py, ../lib/motion_classifier_dataset.py
transfer_output_files = motions.csv
transfer_output_remaps = "motions.csv = file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/motions.csv;"

request_cpus = 1
request_memory = 32GB
request_disk = 32GB



queue 1
